using UnityEngine;

public class MovingPlatform : MonoBehaviour
{
	public Transform pointA;
	public Transform pointB;
	public float speed = 2f;

	private Vector3 target;

	void Start()
	{
		target = pointB.position;
	}

	void Update()
	{
		transform.position = Vector3.MoveTowards(transform.position, target, speed * Time.deltaTime);

		if (Vector3.Distance(transform.position, target) < 0.1f)
		{
			target = (target == pointA.position) ? pointB.position : pointA.position;
		}
	}

	private void OnCollisionEnter2D(Collision2D collision)
	{
		if (collision.gameObject.CompareTag("Player"))
		{
			collision.transform.SetParent(this.transform);
		}
	}

	private void OnCollisionExit2D(Collision2D collision)
	{
		if (collision.gameObject.CompareTag("Player"))
		{
			collision.transform.SetParent(null);
		}
	}
}
